pipeline {
    agent any

    environment {
        PYTHON = '"C:\\Users\\M AKASH REDDY\\AppData\\Local\\Programs\\Python\\Python312\\python.exe"'
        APP_DIR = 'train4\\train4\\weights'  // Updated path to your actual app files
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/rishideep04/Intelligent-Traffic-Management-System.git'
            }
        }

        stage('Setup Environment') {
            steps {
                bat """
                %PYTHON% -m venv venv
                call venv\\Scripts\\activate
                pip install -r %APP_DIR%\\requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                bat """
                call venv\\Scripts\\activate
                cd %APP_DIR%
                python -m unittest discover
                """
            }
        }

        stage('Start Flask App') {
            steps {
                bat """
                call venv\\Scripts\\activate
                cd %APP_DIR%
                python app2.py
                """
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
    }
}
